### ISSUE TITLE
Form inline换行问题

### ISSUE THREAD

**Issue by farzer** [gmfe/react-gm#43]

**Comment by farzer** [comment]
```css
.gm-form.form-inline {
  flex-wrap: wrap
}
```
